name: Update tallies

on:
  workflow_dispatch:
#  schedule:
#  - cron: '55 * * * *'

jobs:
  tally_votes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19.x"
    - uses: actions/checkout@v3 # checks out to /home/work/gov4git
    - shell: bash
      run: |
        echo current directory `pwd`
        echo home directory ~
