name: Update tallies

on:
  workflow_dispatch:
#  schedule:
#  - cron: '55 * * * *'

jobs:
  tally_votes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19.x"
    - uses: actions/checkout@v3 # checks out to /home/runner/work/gov4git
    - shell: bash
      run: |
        echo current directory `pwd`
        echo home directory ~
    - run: .scripts/build-and-tally.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
